// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths.Pet.WithPetID {
    public var uploadImage: UploadImage {
        UploadImage(path: path + "/uploadImage")
    }

    public struct UploadImage {
        /// Path: `/pet/{petId}/uploadImage`
        public let path: String

        /// Uploads an image
        public func post(additionalMetadata: String? = nil, _ body: Data? = nil) -> Request<PetstoreKit.APIResponse> {
            Request(path: path, method: "POST", query: makePostQuery(additionalMetadata), body: body, id: "uploadFile")
        }

        private func makePostQuery(_ additionalMetadata: String?) -> [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(additionalMetadata, forKey: "additionalMetadata")
            return encoder.items
        }
    }
}
