// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths.Store {
    public var order: Order {
        Order(path: path + "/order")
    }

    public struct Order {
        /// Path: `/store/order`
        public let path: String

        /// Place an order for a pet
        ///
        /// Place a new order in the store
        public func post(_ body: PetstoreKit.Order? = nil) -> Request<PetstoreKit.Order> {
            Request(path: path, method: "POST", body: body, id: "placeOrder")
        }
    }
}
