// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths.Store.Order {
    public func orderID(_ orderID: Int) -> WithOrderID {
        WithOrderID(path: "\(path)/\(orderID)")
    }

    public struct WithOrderID {
        /// Path: `/store/order/{orderId}`
        public let path: String

        /// Find purchase order by ID
        ///
        /// For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
        public var get: Request<PetstoreKit.Order> {
            Request(path: path, method: "GET", id: "getOrderById")
        }

        /// Delete purchase order by ID
        ///
        /// For valid response try integer IDs with value < 1000. Anything above 1000 or nonintegers will generate API errors
        public var delete: Request<Void> {
            Request(path: path, method: "DELETE", id: "deleteOrder")
        }
    }
}
