// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths.User {
    public func username(_ username: String) -> WithUsername {
        WithUsername(path: "\(path)/\(username)")
    }

    public struct WithUsername {
        /// Path: `/user/{username}`
        public let path: String

        /// Get user by user name
        public var get: Request<PetstoreKit.User> {
            Request(path: path, method: "GET", id: "getUserByName")
        }

        /// Update user
        ///
        /// This can only be done by the logged in user.
        public func put(_ body: PetstoreKit.User? = nil) -> Request<Void> {
            Request(path: path, method: "PUT", body: body, id: "updateUser")
        }

        /// Delete user
        ///
        /// This can only be done by the logged in user.
        public var delete: Request<Void> {
            Request(path: path, method: "DELETE", id: "deleteUser")
        }
    }
}
