// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct Address: Codable {
    /// Example: "437 Lytton"
    public var street: String?
    /// Example: "Palo Alto"
    public var city: String?
    /// Example: "CA"
    public var state: String?
    /// Example: "94301"
    public var zip: String?

    public init(street: String? = nil, city: String? = nil, state: String? = nil, zip: String? = nil) {
        self.street = street
        self.city = city
        self.state = state
        self.zip = zip
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.street = try values.decodeIfPresent(String.self, forKey: "street")
        self.city = try values.decodeIfPresent(String.self, forKey: "city")
        self.state = try values.decodeIfPresent(String.self, forKey: "state")
        self.zip = try values.decodeIfPresent(String.self, forKey: "zip")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(street, forKey: "street")
        try values.encodeIfPresent(city, forKey: "city")
        try values.encodeIfPresent(state, forKey: "state")
        try values.encodeIfPresent(zip, forKey: "zip")
    }
}
